Automatic cllimbing code
FRC2706/2017-2706-Robot-Code pull request #40
Opened 2017-02-18 21:20 UTC by wakandacat

Hasn't been tested yet as it needs the real robot.

2017-02-18 22:15 UTC, ryanlarkin requested changes
There is one or two minor formatting issues that I can fix before the next meeting.

2017-02-18 22:15 UTC, eandr127 commented on src/org/usfirst/frc/team2706/robot/commands/teleop/ClimbAutomatically.java
> +}
This needs a new line

2017-02-18 22:15 UTC, eandr127 commented on src/org/usfirst/frc/team2706/robot/subsystems/Climber.java
> +    //Verifying if the robot is ready to climb.
This should be Javadoc

2017-02-19 17:34 UTC, ryanlarkin approved these changes

2017-02-25 15:38 UTC, merged