Robot mapping
FRC2706/2017-2706-Robot-Code pull request #50
Opened 2017-03-03 01:06 UTC by eandr127

For some reason, this wasn't included in the merge

2017-03-03 02:01 UTC, Stealth2994 commented
No its not ready yet wait till tomorrow

2017-03-03 02:01 UTC, Stealth2994 commented
We dont merge undocumented and unformatted code into master

2017-03-03 15:25 UTC, greyingjay commented
Controls team is meeting tonight to work on installing the bling and the ring light. You guys are welcome to come and work on software during that time. Or you can do this from home.

2017-03-04 15:14 UTC, eandr127 commented
Do you want me to work on documenting this?

2017-03-04 16:05 UTC, greyingjay commented
Let's work on getting all of our code cleaned up, documented, and in master so we don't waste time trying to keep track of which code is in who's branch, especially code that the drive team needs.

-k

> On Mar 4, 2017, at 10:14 AM, eandr127 <notifications@github.com> wrote:
> 
> Do you want me to work on documenting this?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-03-04 16:24 UTC, cnnradams requested changes
fix small thing

2017-03-04 16:24 UTC, Stealth2994 commented on src/org/usfirst/frc/team2706/robot/commands/mechanismcontrol/CloseGearMechanism.java
> +public class CloseGearMechanism extends Command {
documentation?

2017-03-04 16:24 UTC, Stealth2994 commented on src/org/usfirst/frc/team2706/robot/commands/teleop/TakeOverCommandBrake.java
> +public class TakeOverCommandBrake extends Command {
delete that

2017-03-04 16:29 UTC, cnnradams approved these changes
because were rushed

2017-03-04 16:29 UTC, merged